### PR TITLE
Add spree_auth_devise initializer

### PR DESCRIPTION
**Pull request by enricostano**
#### What? Why?

We're fixing https://github.com/openfoodfoundation/openfoodnetwork/issues/1694
Please read comments in the code to get more context.

#### What should we test?

An order can be captured from admin interface.

#### How is this related to the Spree upgrade?

😬

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
What a dirty hack, but makes sense to me. Unfortunately Rob is going away for a few weeks. He has a bit more knowledge about this.

**Comment by sauloperez** [comment]
@mkllnk believe me this is the least worst hack :trollface: Jokes aside, we're doing something that `spree` and OFN already do. Check https://github.com/spree/spree/blob/1-3-stable/api/lib/spree/api/engine.rb#L23 and https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/application.rb#L17

**Comment by enricostano** [comment]
Going to merge this so we can test it in AUS staging1.

I know it's a dirty hack but this is the best could find. Any suggestion is welcome, until we merge step 6 branch into `master`.

**Comment by mkllnk** [comment]
Sorry, I didn't want to criticise you. I think it's a really good solution for the problem. It's just shocking that these measures are necessary. I'm sharing your frustration with Spree.

**Comment by sauloperez** [comment]
No offense taken @mkllnk, we know and feel that frustration, believe me :trollface:

**Pull request merged**
