### PR TITLE
Add clone json endpoint

### PR DESCRIPTION
**Pull request by enricostano**
### The problem
There is a [feature spec](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/features/admin/bulk_product_update_spec.rb#L413) failing because the current view is using an endpoint which response has changed in more recent Spree.

```
     Failure/Error: expect(page.find("#status-message")).to have_content "Changes saved."
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
       
       Error: undefined is not an object (evaluating 'data.product.id')
```

The problem is that the `GET /admin/products/:product_permalink/clone.json` endpoint changed its internals and cannot be overridden. Basically before it was using `#respond_with()` but now it's using `#redirect_to()`.

**Spree::Admin::ProductsController#clone** [right now](https://github.com/openfoodfoundation/spree/blob/spree-upgrade-step1c/core/app/controllers/spree/admin/products_controller.rb#L55) vs [in the Spree upgrade branch](https://github.com/openfoodfoundation/spree/blob/spree-upgrade-step-3/backend/app/controllers/spree/admin/products_controller.rb#L57)

This change makes all the responses to be HTML and it breaks the `data.product.id` in the view since it was expecting a JS object instead.

### A possible solution
Our proposal is to add a new JSON endpoint to the API:
```
GET /api/products/:product_id/clone
```
In this way we call a pure JSON endpoint from a AJAX call instead of reusing an HTML one.

### Problems
In our opinion this endpoint should be use a `POST` verb since it's modifying the internal state. `GET` requests should always be idempotent.

The problem is that I couldn't find any JS helper to make the AJAX call. The `dataFetch()` helper only manages (correctly) `GET` requests. Do we have already a helper for `POST` requests somewhere? We justs didn't want to throw a `$.ajax()` in there 😬

### CODE REVIEW

**Comment by sseerrggii** [comment]
Nice

**Comment by oeoeaio** [comment]
@enricostano @Em-AK 

Looks pretty good to me. I wrote the dataFetcher logic very early on in my Angular career, so I don't have a lot of confidence that it is the best way to make such a simple request. It looks like it is just wrapping the response in a promise (which is pointless - it is already wrapped in a promise), and registering the request with the RequestMonitor which is mostly used for displaying a 'Loading' flash (not required in this instance). So I think using dataFetcher not really necessary. I would probably just use a [$http.put()](https://docs.angularjs.org/api/ng/service/$http) call...

**Comment by enricostano** [comment]
Thanks @oeoeaio !

I finally used `POST` and `$http.post()` since this is an RPC endpoint that creates new resources from existing one. `PUT` should be used for less invasive changes IMHO.

**Comment by Em-AK** [comment]
Specs are green, on the HEAD commit : https://travis-ci.org/Em-AK/openfoodnetwork/builds/219226891
might be a GH bug after I forced pushed on the branch.

**Pull request merged**
